name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Grant execute permissions to selenium-manager
        run: |
          chmod +x ./Specflow_Selenium_Parallel/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
      - name: Run headless Specflow test
        uses: coactions/setup-xvfb@v1
        with:
          working-directory: ./Specflow_Selenium_Parallel
          run: dotnet test --no-build --verbosity normal
        continue-on-error: true
       # Step 9: List the directory to verify Extent_Reports location
      - name: List project directory contents
        run: |
          ls -R ${{ github.workspace }}/Specflow_Selenium_Parallel/bin/debug/net6.0/Extent_Reports  # Recursively list files to verify the report path
          echo ${{ github.workspace }}/Specflow_Selenium_Parallel/bin/debug/net6.0/Extent_Reports
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
           # Artifact name
          name: SpecflowReport
        # A file, directory or wildcard pattern that describes what to upload
          path: "${{ github.workspace }}/Specflow_Selenium_Parallel/bin/debug/net6.0/Extent_Reports"
